# Generated by Django 6.0.6 on 2026-07-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "shot_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "source_local_path",
                    models.CharField(
                        help_text="raw provenance.source path", max_length=1000
                    ),
                ),
                ("s3_bucket", models.CharField(blank=True, max_length=200)),
                ("s3_key", models.CharField(blank=True, max_length=1000)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("caller_state", models.CharField(blank=True, max_length=100)),
                ("caller_country", models.CharField(blank=True, max_length=100)),
                ("detected_language", models.CharField(blank=True, max_length=20)),
                (
                    "source_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assist_brief", models.TextField(blank=True)),
                ("assist_detailed", models.TextField(blank=True)),
                ("request_brief", models.TextField(blank=True)),
                ("request_detailed", models.TextField(blank=True)),
                (
                    "request_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "request",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "interaction_pattern",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "capture_medium",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "capture_quality",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "setting",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "weather",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "environment_domain",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "outcome",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ingestion_error", models.TextField(blank=True)),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="full original JSONL record, for detail display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="ingestion.upload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segment_id",
                    models.CharField(
                        help_text="source event_id", max_length=200, unique=True
                    ),
                ),
                ("start_s", models.FloatField()),
                ("end_s", models.FloatField()),
                ("label", models.CharField(blank=True, max_length=500)),
                (
                    "text",
                    models.TextField(
                        help_text="label + summary, embedded and keyword-indexed"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="evidence.scores.fusion_score"
                    ),
                ),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True, help_text="float32 vector bytes", null=True
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video_id", "start_s"],
                "indexes": [
                    models.Index(
                        fields=["video", "start_s"],
                        name="videos_segm_video_i_5bbdfa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facet", models.CharField(db_index=True, max_length=100)),
                ("value", models.CharField(db_index=True, max_length=150)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facet", "value"], name="videos_vide_facet_a4b483_idx"
                    )
                ],
                "unique_together": {("video", "facet", "value")},
            },
        ),
    ]
