# Generated by Django 6.0.6 on 2026-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="shot_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
