# Generated by Django 6.0.6 on 2026-07-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxonomyFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=150)),
                (
                    "multi_select",
                    models.BooleanField(
                        default=False,
                        help_text="True for facets that can hold several values per video (tags), False for single-select facets stored directly on Video.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SlugField(max_length=150)),
                ("label", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="taxonomy.taxonomyfacet",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "value"],
                "unique_together": {("facet", "value")},
            },
        ),
    ]
